version: '3.8'

services:  
  postgres:
    container_name: 86002_postgres_container
    image: postgres:14.2
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - postgres:/data/postgres
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - postgres
    restart: unless-stopped

  redis:
    container_name: 86002_redis_container
    image: redis:alpine
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    volumes:
      - redis:/data/redis
    ports:
      - '${REDIS_PORT}:6379'

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  redis: